from __future__ import annotations

import plistlib
import unittest
from tempfile import TemporaryDirectory
from pathlib import Path

from scripts.verify_frontend_package import (
    REQUIRED_RUNTIME_SOURCE_FILES,
    REQUIRED_UI_FILES,
    collect_errors,
    frontend_bundle_source_digest,
)
from scripts.verify_packaged_app import collect_package_errors


PROJECT_ROOT = Path(__file__).resolve().parent


class TestPackagingFrontendManifest(unittest.TestCase):
    def _write_frontend_project(self, project_root: Path) -> None:
        ui_root = project_root / "ui_prototype"
        vendor_root = ui_root / "vendor"
        scripts_root = project_root / "scripts"
        build_vendor_root = scripts_root / "vendor"
        assets_root = project_root / "assets"
        vendor_root.mkdir(parents=True)
        build_vendor_root.mkdir(parents=True)
        assets_root.mkdir(parents=True)
        (ui_root / "art.jsx").write_text("const Art = () => null;\n", encoding="utf-8")
        (ui_root / "tweaks-panel.jsx").write_text("const Tweaks = () => null;\n", encoding="utf-8")
        (ui_root / "app.jsx").write_text("const App = () => null;\n", encoding="utf-8")
        (scripts_root / "build_frontend_bundle.mjs").write_text("console.log('build');\n", encoding="utf-8")
        (scripts_root / "render_hwp_with_rhwp_core.mjs").write_text("console.log('render');\n", encoding="utf-8")
        (build_vendor_root / "babel.min.js").write_text("// babel build tool\n", encoding="utf-8")
        (assets_root / "app_icon.png").write_bytes(b"png")
        (ui_root / "index.html").write_text("<!doctype html>\n", encoding="utf-8")
        (ui_root / "reorder.js").write_text("// reorder\n", encoding="utf-8")
        (ui_root / "review_filters.js").write_text("// filters\n", encoding="utf-8")
        (ui_root / "publish_summary.js").write_text("// summary\n", encoding="utf-8")
        (ui_root / "publish_guard.js").write_text("// guard\n", encoding="utf-8")
        (vendor_root / "react.production.min.js").write_text("// react\n", encoding="utf-8")
        (vendor_root / "react-dom.production.min.js").write_text("// react-dom\n", encoding="utf-8")
        digest = frontend_bundle_source_digest(project_root)
        self.assertIsNotNone(digest)
        (ui_root / "app.bundle.js").write_text(
            "/*\n"
            " * Generated by scripts/build_frontend_bundle.mjs.\n"
            f" * Source SHA256: {digest}\n"
            " */\n"
            "/* app.jsx */\n",
            encoding="utf-8",
        )
        (ui_root / "board.html").write_text(
            f'<!doctype html><script src="app.bundle.js?v=frontend-bundle-{digest}"></script>\n',
            encoding="utf-8",
        )
        manifest_text = "\n".join((*REQUIRED_UI_FILES, *REQUIRED_RUNTIME_SOURCE_FILES)) + "\n"
        for manifest_name in ("ClassInEDBMVP.spec", "package_macos_app.sh", "package_mvp.ps1"):
            (project_root / manifest_name).write_text(manifest_text, encoding="utf-8")

    def _write_packaged_runtime(self, package_root: Path, resource_rel: str = "_internal") -> Path:
        resource_root = package_root / resource_rel
        ui_root = resource_root / "ui_prototype"
        vendor_root = ui_root / "vendor"
        scripts_root = resource_root / "scripts"
        assets_root = resource_root / "assets"
        vendor_root.mkdir(parents=True)
        scripts_root.mkdir(parents=True)
        assets_root.mkdir(parents=True)
        (resource_root / "app_update_config.json").write_text(
            '{"appName":"ClassInEDBMVP","version":"test"}\n',
            encoding="utf-8",
        )
        (scripts_root / "render_hwp_with_rhwp_core.mjs").write_text("console.log('ok');\n", encoding="utf-8")
        (assets_root / "app_icon.png").write_bytes(b"png")
        (ui_root / "index.html").write_text("<!doctype html>\n", encoding="utf-8")
        digest = "0" * 64
        (ui_root / "board.html").write_text(
            f'<!doctype html><script src="app.bundle.js?v=frontend-bundle-{digest}"></script>\n',
            encoding="utf-8",
        )
        (ui_root / "reorder.js").write_text("// reorder\n", encoding="utf-8")
        (ui_root / "review_filters.js").write_text("// filters\n", encoding="utf-8")
        (ui_root / "publish_summary.js").write_text("// summary\n", encoding="utf-8")
        (ui_root / "publish_guard.js").write_text("// guard\n", encoding="utf-8")
        (ui_root / "app.bundle.js").write_text(
            "/*\n"
            " * Generated by scripts/build_frontend_bundle.mjs.\n"
            f" * Source SHA256: {digest}\n"
            " */\n"
            "/* app.jsx */\n",
            encoding="utf-8",
        )
        (vendor_root / "react.production.min.js").write_text("// react\n", encoding="utf-8")
        (vendor_root / "react-dom.production.min.js").write_text("// react-dom\n", encoding="utf-8")
        return resource_root

    def _write_macos_info_plist(
        self,
        package_root: Path,
        version: str = "test",
        bundle_id: str = "local.classin.edbmvp",
    ) -> None:
        contents_root = package_root / "Contents"
        contents_root.mkdir(parents=True, exist_ok=True)
        (contents_root / "Info.plist").write_bytes(
            plistlib.dumps(
                {
                    "CFBundleIdentifier": bundle_id,
                    "CFBundleName": "ClassInEDBMVP",
                    "CFBundleShortVersionString": version,
                    "CFBundleVersion": version,
                },
                sort_keys=True,
            )
        )

    def test_frontend_package_manifest_is_current(self) -> None:
        self.assertEqual([], collect_errors(PROJECT_ROOT))

    def test_frontend_package_rejects_stale_bundle_source_digest(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "ui_prototype" / "app.jsx").write_text("const App = () => 'changed';\n", encoding="utf-8")
            errors = collect_errors(project_root)

        self.assertTrue(any("source digest is stale" in error for error in errors))

    def test_frontend_package_rejects_bundle_built_with_old_bundler(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "scripts" / "build_frontend_bundle.mjs").write_text(
                "console.log('changed build script');\n",
                encoding="utf-8",
            )
            errors = collect_errors(project_root)

        self.assertTrue(any("source digest is stale" in error for error in errors))

    def test_frontend_package_rejects_bundle_built_with_old_babel_transformer(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "scripts" / "vendor" / "babel.min.js").write_text(
                "// changed babel build tool\n",
                encoding="utf-8",
            )
            errors = collect_errors(project_root)

        self.assertTrue(any("source digest is stale" in error for error in errors))

    def test_frontend_package_rejects_bundle_without_source_digest(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            (project_root / "ui_prototype" / "app.bundle.js").write_text(
                "/* Generated by scripts/build_frontend_bundle.mjs */\n/* app.jsx */\n",
                encoding="utf-8",
            )

            errors = collect_errors(project_root)

        self.assertTrue(any("missing the source digest" in error for error in errors))

    def test_frontend_package_rejects_stale_board_cache_bust(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "ui_prototype" / "board.html").write_text(
                f'<!doctype html><script src="app.bundle.js?v=frontend-bundle-{"1" * 64}"></script>\n',
                encoding="utf-8",
            )
            errors = collect_errors(project_root)

        self.assertTrue(any("cache bust is stale" in error for error in errors))

    def test_frontend_package_rejects_browser_side_babel_in_ui_assets(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "ui_prototype" / "vendor" / "babel.min.js").write_text(
                "// old browser-side babel\n",
                encoding="utf-8",
            )
            errors = collect_errors(project_root)

        self.assertTrue(any("ui_prototype/vendor/babel.min.js" in error for error in errors))

    def test_frontend_package_rejects_missing_runtime_source_asset(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            (project_root / "scripts" / "render_hwp_with_rhwp_core.mjs").unlink()
            errors = collect_errors(project_root)

        self.assertTrue(any("missing required runtime asset" in error for error in errors))

    def test_frontend_package_rejects_manifest_missing_runtime_source_asset(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            project_root = Path(raw_tmp)
            self._write_frontend_project(project_root)
            self.assertEqual([], collect_errors(project_root))

            manifest = "\n".join(REQUIRED_UI_FILES) + "\n"
            (project_root / "ClassInEDBMVP.spec").write_text(manifest, encoding="utf-8")
            errors = collect_errors(project_root)

        self.assertTrue(any("ClassInEDBMVP.spec does not include runtime asset" in error for error in errors))

    def test_packaged_app_layout_accepts_current_runtime_assets(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            self._write_packaged_runtime(package_root)

            self.assertEqual([], collect_package_errors(package_root))

    def test_packaged_app_layout_rejects_legacy_browser_runtime(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            ui_root = resource_root / "ui_prototype"
            (ui_root / "vendor" / "babel.min.js").write_text("// babel\n", encoding="utf-8")
            (ui_root / "board.html").write_text(
                '<!doctype html><script src="app.js?v=old-ui"></script>\n',
                encoding="utf-8",
            )

            errors = collect_package_errors(package_root)

        self.assertTrue(any("babel.min.js" in error for error in errors))
        self.assertTrue(any("app.js?v=" in error for error in errors))

    def test_packaged_app_layout_rejects_bundle_without_source_digest(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            (resource_root / "ui_prototype" / "app.bundle.js").write_text(
                "/* Generated by scripts/build_frontend_bundle.mjs */\n/* app.jsx */\n",
                encoding="utf-8",
            )

            errors = collect_package_errors(package_root)

        self.assertTrue(any("source digest" in error for error in errors))

    def test_packaged_app_layout_rejects_board_cache_bust_mismatch(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            (resource_root / "ui_prototype" / "board.html").write_text(
                f'<!doctype html><script src="app.bundle.js?v=frontend-bundle-{"1" * 64}"></script>\n',
                encoding="utf-8",
            )

            errors = collect_package_errors(package_root)

        self.assertTrue(any("cache bust does not match" in error for error in errors))

    def test_packaged_app_layout_rejects_unexpected_update_metadata(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            self._write_packaged_runtime(package_root)

            errors = collect_package_errors(
                package_root,
                expected_app_name="ClassInEDBMVP",
                expected_version="0.2.0",
            )

        self.assertTrue(any("version mismatch" in error for error in errors))

    def test_packaged_app_layout_rejects_macos_info_plist_version_mismatch(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP.app"
            self._write_packaged_runtime(package_root, "Contents/Resources")
            self._write_macos_info_plist(package_root, version="0.9.0")

            errors = collect_package_errors(package_root)

        self.assertTrue(any("CFBundleShortVersionString mismatch" in error for error in errors))
        self.assertTrue(any("CFBundleVersion mismatch" in error for error in errors))

    def test_packaged_app_layout_rejects_macos_bundle_identifier_mismatch(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP.app"
            self._write_packaged_runtime(package_root, "Contents/Resources")
            self._write_macos_info_plist(package_root, bundle_id="com.example.old-edb")

            errors = collect_package_errors(
                package_root,
                expected_bundle_id="local.classin.edbmvp",
            )

        self.assertTrue(any("CFBundleIdentifier mismatch" in error for error in errors))

    def test_packaged_app_layout_rejects_missing_macos_info_plist(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP.app"
            self._write_packaged_runtime(package_root, "Contents/Resources")

            errors = collect_package_errors(package_root)

        self.assertTrue(any("missing macOS app bundle Info.plist" in error for error in errors))

    def test_packaged_app_layout_rejects_runtime_session_artifacts(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            (package_root / ".app_runtime" / "outputs").mkdir(parents=True)
            (resource_root / "latest_session.json").write_text('{"problems":[]}\n', encoding="utf-8")
            (resource_root / "uploads").mkdir()

            errors = collect_package_errors(package_root)

        self.assertTrue(any(".app_runtime" in error for error in errors))
        self.assertTrue(any("latest_session.json" in error for error in errors))
        self.assertTrue(any("uploads" in error for error in errors))

    def test_packaged_app_layout_rejects_build_time_frontend_tools(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            (resource_root / "scripts" / "vendor").mkdir()
            (resource_root / "scripts" / "build_frontend_bundle.mjs").write_text(
                "console.log('build');\n",
                encoding="utf-8",
            )
            (resource_root / "scripts" / "vendor" / "babel.min.js").write_text(
                "// build-time babel\n",
                encoding="utf-8",
            )
            (resource_root / "scripts" / "verify_frontend_package.py").write_text(
                "print('dev verifier')\n",
                encoding="utf-8",
            )

            errors = collect_package_errors(package_root)

        self.assertTrue(any("scripts/build_frontend_bundle.mjs" in error for error in errors))
        self.assertTrue(any("scripts/vendor" in error for error in errors))
        self.assertTrue(any("scripts/verify_frontend_package.py" in error for error in errors))

    def test_packaged_app_layout_rejects_source_asset_files(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP"
            resource_root = self._write_packaged_runtime(package_root)
            (resource_root / "assets" / "app_icon.svg").write_text("<svg />\n", encoding="utf-8")
            (resource_root / "assets" / "brand_mark.svg").write_text("<svg />\n", encoding="utf-8")

            errors = collect_package_errors(package_root)

        self.assertTrue(any("assets/app_icon.svg" in error for error in errors))
        self.assertTrue(any("assets/brand_mark.svg" in error for error in errors))

    def test_packaged_app_layout_dedupes_macos_resource_symlinks(self) -> None:
        with TemporaryDirectory() as raw_tmp:
            package_root = Path(raw_tmp) / "ClassInEDBMVP.app"
            frameworks_root = package_root / "Contents" / "Frameworks"
            self._write_packaged_runtime(package_root, "Contents/Resources")
            self._write_macos_info_plist(package_root)
            frameworks_root.mkdir(parents=True)
            try:
                (frameworks_root / "ui_prototype").symlink_to("../Resources/ui_prototype", target_is_directory=True)
                (frameworks_root / "scripts").symlink_to("../Resources/scripts", target_is_directory=True)
                (frameworks_root / "app_update_config.json").symlink_to("../Resources/app_update_config.json")
            except OSError as exc:
                raise unittest.SkipTest(f"symlink creation is not available: {exc}") from exc

            self.assertEqual([], collect_package_errors(package_root))

    def test_packaging_scripts_run_frontend_package_verifier(self) -> None:
        for rel_path in ("ClassInEDBMVP.spec", "package_macos_app.sh", "package_mvp.ps1"):
            with self.subTest(rel_path=rel_path):
                source = (PROJECT_ROOT / rel_path).read_text(encoding="utf-8")
                if rel_path.endswith(".spec"):
                    self.assertIn("collect_errors", source)
                    self.assertIn("verify_frontend_package()", source)
                else:
                    self.assertIn("scripts/verify_frontend_package.py".replace("/", "\\" if rel_path.endswith(".ps1") else "/"), source)

    def test_packaging_scripts_verify_frontend_after_optional_bundle_build(self) -> None:
        shell_source = (PROJECT_ROOT / "package_macos_app.sh").read_text(encoding="utf-8")
        self.assertLess(
            shell_source.index("scripts/build_frontend_bundle.mjs"),
            shell_source.index("scripts/verify_frontend_package.py"),
        )

        ps_source = (PROJECT_ROOT / "package_mvp.ps1").read_text(encoding="utf-8")
        self.assertLess(
            ps_source.index("scripts\\build_frontend_bundle.mjs"),
            ps_source.index("scripts\\verify_frontend_package.py"),
        )

        spec_source = (PROJECT_ROOT / "ClassInEDBMVP.spec").read_text(encoding="utf-8")
        self.assertLess(spec_source.index("verify_frontend_package()"), spec_source.index("a = Analysis("))

    def test_frontend_bundle_builder_updates_board_cache_bust(self) -> None:
        source = (PROJECT_ROOT / "scripts" / "build_frontend_bundle.mjs").read_text(encoding="utf-8")
        self.assertIn("board.html", source)
        self.assertIn("frontend-bundle-${sourceDigest}", source)

    def test_packaging_scripts_run_built_artifact_verifier(self) -> None:
        for rel_path in ("package_macos_app.sh", "package_mvp.ps1", "package_windows_installer.ps1"):
            with self.subTest(rel_path=rel_path):
                source = (PROJECT_ROOT / rel_path).read_text(encoding="utf-8")
                self.assertIn(
                    "scripts/verify_packaged_app.py".replace("/", "\\" if rel_path.endswith(".ps1") else "/"),
                    source,
                )

    def test_windows_source_package_fallback_copies_only_runtime_scripts(self) -> None:
        source = (PROJECT_ROOT / "package_mvp.ps1").read_text(encoding="utf-8")
        self.assertIn('"scripts\\render_hwp_with_rhwp_core.mjs"', source)
        self.assertNotRegex(source, r'(?m)^\s+"scripts",\s*$')

    def test_windows_source_package_fallback_copies_only_runtime_assets(self) -> None:
        source = (PROJECT_ROOT / "package_mvp.ps1").read_text(encoding="utf-8")
        self.assertIn('"assets\\app_icon.png"', source)
        self.assertNotRegex(source, r'(?m)^\s+"assets",\s*$')

    def test_windows_source_package_fallback_uses_generated_update_config(self) -> None:
        source = (PROJECT_ROOT / "package_mvp.ps1").read_text(encoding="utf-8")
        self.assertNotRegex(source, r'(?m)^\s+"app_update_config\.json",\s*$')
        self.assertIn('Copy-Item -Force $BuildUpdateConfig (Join-Path $PackageRoot "app_update_config.json")', source)

    def test_packaging_scripts_verify_expected_update_metadata(self) -> None:
        shell_source = (PROJECT_ROOT / "package_macos_app.sh").read_text(encoding="utf-8")
        self.assertIn('--expected-app-name "$APP_NAME"', shell_source)
        self.assertIn('--expected-version "$EFFECTIVE_APP_VERSION"', shell_source)
        self.assertIn('--expected-bundle-id "$BUNDLE_ID"', shell_source)

        ps_source = (PROJECT_ROOT / "package_mvp.ps1").read_text(encoding="utf-8")
        self.assertIn("--expected-app-name $EffectiveAppName", ps_source)
        self.assertIn("--expected-version $EffectiveAppVersion", ps_source)

        installer_source = (PROJECT_ROOT / "package_windows_installer.ps1").read_text(encoding="utf-8")
        self.assertIn('"--expected-app-name"', installer_source)
        self.assertIn('"--expected-version"', installer_source)

    def test_windows_installer_derives_version_from_packaged_update_metadata(self) -> None:
        source = (PROJECT_ROOT / "package_windows_installer.ps1").read_text(encoding="utf-8")
        self.assertIn("Read-PackagedUpdateConfig", source)
        self.assertIn('$EffectiveInstallerVersion = if ($Version) { $Version } else { $PackagedVersion }', source)
        self.assertIn('"--expected-version"', source)
        self.assertIn("$EffectiveInstallerVersion", source)
        self.assertIn('"/DAppVersion=$EffectiveInstallerVersion"', source)
        self.assertNotIn('"/DAppVersion=$Version"', source)

    def test_windows_installer_verifies_existing_app_before_installer_build(self) -> None:
        source = (PROJECT_ROOT / "package_windows_installer.ps1").read_text(encoding="utf-8")
        verifier_index = source.index("scripts\\verify_packaged_app.py")
        self.assertLess(source.index("PyInstaller app output was not found"), verifier_index)
        self.assertLess(verifier_index, source.index("if ($Sign -and $SkipAppBuild)"))
        self.assertLess(verifier_index, source.index("$Iscc = Find-InnoSetupCompiler"))

    def test_ci_installer_workflow_uses_packaging_wrappers(self) -> None:
        workflow = (PROJECT_ROOT / ".github" / "workflows" / "build-installers.yml").read_text(encoding="utf-8")
        self.assertIn("actions/setup-node@v4", workflow)
        self.assertIn("./package_macos_app.sh", workflow)
        self.assertIn(".\\package_windows_installer.ps1", workflow)
        self.assertNotIn("-SkipFrontendBuild", workflow)
        self.assertNotIn("-SkipAppBuild", workflow)
        self.assertLess(workflow.index("./package_macos_app.sh"), workflow.index("dist/ClassInEDBMVP-macOS.dmg"))
        self.assertLess(workflow.index(".\\package_windows_installer.ps1"), workflow.index("dist/ClassInEDBMVP-Setup.exe"))
        self.assertLess(workflow.index("- macos"), workflow.index("python scripts/build_update_feed.py"))
        self.assertLess(workflow.index("- windows"), workflow.index("python scripts/build_update_feed.py"))


if __name__ == "__main__":
    unittest.main()
