name = "classin-edb-reports"
main = "src/index.js"
compatibility_date = "2026-07-27"
workers_dev = false

[[routes]]
pattern = "reports.classin.cloud"
custom_domain = true

[[d1_databases]]
binding = "REPORTS_DB"
database_name = "classin-edb-reports"
database_id = "de4913d5-9f19-433b-abfa-763694429549"
migrations_dir = "migrations"
